//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSkillsYachts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public System.DateTime RegisteredDate { get; set; }
        public bool IsBlocked { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> PasswordChanged { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
